### ISSUE TITLE
服务器上的redis mysql密码都传上来了

### ISSUE THREAD

**Issue by hakusai22** [HildaM/bytedance-douyin#1]

**Comment by HildaM** [comment]
失误。。。。谢谢提醒！

**Comment by hakusai22** [comment]
你们视频是上传到服务器吗 看代码是保存到本地。获取列表的时候又是带服务器地址

**Comment by hakusai22** [comment]
我想问一下 我使用的是android studio模拟器 将视频存储到本地 使用postman进行调用返回的视频地址可以播放，但是在模拟器上就就播放不了，
![image](https://user-images.githubusercontent.com/58761705/170160254-3e5f3531-f9bd-462e-bf4f-86cd64c8c085.png)

**Comment by hakusai22** [comment]
![image](https://user-images.githubusercontent.com/58761705/170160712-6351f0bb-15af-4a58-a577-497ad6155a51.png)
评论这边post请求 token在路径上 post表单里面token这样直接获取不到呀 apk版本我下的最新版

**Comment by HildaM** [comment]
> 我想问一下 我使用的是android studio模拟器 将视频存储到本地 使用postman进行调用返回的视频地址可以播放，但是在模拟器上就就播放不了， ![image](https://user-images.githubusercontent.com/58761705/170160254-3e5f3531-f9bd-462e-bf4f-86cd64c8c085.png)

我们是在服务器上拉起服务，然后用真机测试

**Comment by HildaM** [comment]
> ![image](https://user-images.githubusercontent.com/58761705/170160712-6351f0bb-15af-4a58-a577-497ad6155a51.png) 评论这边post请求 直接拒绝访问 token在路径上 post表单里面token这样直接获取不到呀 apk版本我下的最新版

这个模块并不是我实现的。
现在项目已经进入到优化阶段，所以有一些模块会重写或改造，这里的GitHub仓库仅仅只是我自己的同步自己的分支所用，项目最新进展在gitee中。这里的仓库不会再继续更新了，下一次更新就是在青训营结束的时候。
如果有项目参考需求的话，可以关注我们的gitee仓库
